# denite
[[plugins]]
repo = 'Shougo/denite.nvim'
on_source = ['denite']
# file_mru で シンボリックファイルを表示
hook_add = '''
  let g:neomru#follow_links = 1 
'''

# defx(キーバインドや記号の自作が必要だが、軽い) vs nerdtree
#[[plugins]]
#repo = 'Shougo/defx.nvim'
#on_cmd = ['defx']
[[plugins]]
repo = 'preservim/nerdtree'
on_cmd = ['nerdtree']
hook_add = '''
  let g:NERDTreeShowHidden = 1
'''

